### PR TITLE
Include coverage badge

### PR DESCRIPTION
**Pull request by starsinmypockets**
Include coverage report and coverage badge for README

### CODE REVIEW

**Comment by starsinmypockets** [comment]
OK @anuveyatsu I'll take a look

**Comment by anuveyatsu** [comment]
@starsinmypockets I guess this PR can be closed?

**Comment by starsinmypockets** [comment]
Closed

**Comment by starsinmypockets** [comment]
Handled here instead: https://github.com/datopian/datapackage-views-js/pull/16

**Pull request closed without merging**
